### PR TITLE
Fix encoding for headers and properties if using nested headers

### PR DESCRIPTION
**Pull request by TomFreudenberg**
Hi Michael ( @michaelklishin )

this fix will make nested headers

### CODE REVIEW

**Comment by michaelklishin** [comment]
@TomFreudenberg it would be useful to also add a couple of tests for the recent changes. Then we can cut a new release.

**Comment by TomFreudenberg** [comment]
ok, how much do you expect?

**Comment by michaelklishin** [comment]
There are two key cases:

 * Headers without nested hashes
 * Headers with nested hashes

so 2 new tests seems sufficient to me.

**Comment by TomFreudenberg** [comment]
ok, I prepare them an send in PR

Thanks for already accepting and merging

**Comment by TomFreudenberg** [comment]
@michaelklishin - I will prepare 4 tests:

1 simple header ASCII only
1 nested header ASCII only
1 simple header UTF-8 encodings and ASCII mixed
1 nested header UTF-8 encodings and ASCII mixed

So we test all parts in deep, ok?

**Comment by michaelklishin** [comment]
@TomFreudenberg sounds good, although I think we already have tests for hash serialisation in tables, so the ASCII-only cases are probably covered. But no objections from me, thank you!

**Comment by TomFreudenberg** [comment]
Ok, I will keep them short

**Comment by michaelklishin** [comment]
@TomFreudenberg sorry, do you still plan to contribute a few extra tests? It's OK if not but I need to know when it's a good time to cut a release. Thank you!

**Comment by TomFreudenberg** [comment]
Hi @michaelklishin - yes I will create the tests - sorry to be so late yet

I have created an appointment on next sunday for that.

Tom

**Pull request merged**
