### PR TITLE
most of the way to rspec 3

### PR DESCRIPTION
**Pull request by dbyron0**
There a few failures remaining that I haven't resolved yet. I see them with both ruby 1.9.3-p392 and ruby 2.2.1, though there's an extra one with 1.9.3 Would love a hand.

The 1.9.3 failures
```
 1) AMQ::Protocol::Frame.encode should include final octet
     Failure/Error: expect(Frame.encode(:body, "test", 12).bytes.last).to eq("CE".hex)
     NoMethodError:
       undefined method `last' for #<Enumerator: "\x03\x00\f\x00\x00\x00\x04test\xCE":bytes>
     # ./spec/amq/protocol/frame_spec.rb:51:in `block (3 levels) in <module:Protocol>'
  2) AMQ::Protocol::Table.encode should serialize { :coordinates => { :latitude  => 59.35 } }
     Failure/Error: expect(Table.encode(:coordinates => { :latitude  => 59.35 })).to eql("\x00\x00\x00#\vcoordinatesF\x00\x00\x00\x12\blatituded@M\xAC\xCC\xCC\xCC\xCC\xCD")
       
       expected: "\u0000\u0000\u0000#\vcoordinatesF\u0000\u0000\u0000\u0012\blatituded@M\xAC\xCC\xCC\xCC\xCC\xCD"
            got: "\x00\x00\x00#\vcoordinatesF\x00\x00\x00\x12\blatituded@M\xAC\xCC\xCC\xCC\xCC\xCD"
       
       (compared using eql?)
     # ./spec/amq/protocol/table_spec.rb:61:in `block (3 levels) in <module:Protocol>'

  3) AMQ::Protocol::Table.encode should serialize { :coordinates => { :longitude => 18.066667 } }
     Failure/Error: expect(Table.encode(:coordinates => { :longitude => 18.066667 })).to eql("\x00\x00\x00$\vcoordinatesF\x00\x00\x00\x13\tlongituded@2\x11\x11\x16\xA8\xB8\xF1")
       
       expected: "\u0000\u0000\u0000$\vcoordinatesF\u0000\u0000\u0000\u0013\tlongituded@2\u0011\u0011\u0016\xA8\xB8\xF1"
            got: "\x00\x00\x00$\vcoordinatesF\x00\x00\x00\x13\tlongituded@2\x11\x11\x16\xA8\xB8\xF1"
       
       (compared using eql?)
     # ./spec/amq/protocol/table_spec.rb:65:in `block (3 levels) in <module:Protocol>'

  4) AMQ::Protocol::Table.encode should return "\u0000\u0000\u0000\u000F\u0005floatd?\xFE\xB8Q\xEB\x85\u001E\xB8" for {"float"=>1.92}
     Failure/Error: expect(Table.encode(data)).to eql(encoded)
       
       expected: "\u0000\u0000\u0000\u000F\u0005floatd?\xFE\xB8Q\xEB\x85\u001E\xB8"
            got: "\x00\x00\x00\x0F\x05floatd?\xFE\xB8Q\xEB\x85\x1E\xB8"
       
       (compared using eql?)
     # ./spec/amq/protocol/table_spec.rb:70:in `block (4 levels) in <module:Protocol>'

  5) AMQ::Protocol::Table.decode is capable of decoding string table values with UTF-8 characters
     Failure/Error: expect(Table.decode(Table.encode(input))).to eq(input)
     ArgumentError:
       Not a valid type: "?"
       Data: "\u0000\u0000\u0000\"\f??????S\u0000\u0000\u0000\u0010????????"
       Unprocessed data: "??????"
       Offset: 18
       Total size: 34
       Processed data: {}
     # ./lib/amq/protocol/table.rb:105:in `decode'
     # ./spec/amq/protocol/table_spec.rb:114:in `block (3 levels) in <module:Protocol>'

  6) AMQ::Protocol::Table.decode is capable of decoding deeply nested tables
     Failure/Error: expect(Table.decode(Table.encode(input))).to eq(input)
     Encoding::CompatibilityError:
       incompatible character encodings: ASCII-8BIT and UTF-8
     # ./lib/amq/protocol/table.rb:42:in `block in encode'
     # ./lib/amq/protocol/table.rb:35:in `each'
     # ./lib/amq/protocol/table.rb:35:in `encode'
     # ./lib/amq/protocol/table.rb:42:in `block in encode'
     # ./lib/amq/protocol/table.rb:35:in `each'
     # ./lib/amq/protocol/table.rb:35:in `encode'
     # ./lib/amq/protocol/table.rb:42:in `block in encode'
     # ./lib/amq/protocol/table.rb:35:in `each'
     # ./lib/amq/protocol/table.rb:35:in `encode'
     # ./spec/amq/protocol/table_spec.rb:221:in `block (3 levels) in <module:Protocol>'

Finished in 0.1339 seconds (files took 0.28567 seconds to load)
412 examples, 6 failures

Failed examples:

rspec ./spec/amq/protocol/frame_spec.rb:50 # AMQ::Protocol::Frame.encode should include final octet
rspec ./spec/amq/protocol/table_spec.rb:60 # AMQ::Protocol::Table.encode should serialize { :coordinates => { :latitude  => 59.35 } }
rspec ./spec/amq/protocol/table_spec.rb:64 # AMQ::Protocol::Table.encode should serialize { :coordinates => { :longitude => 18.066667 } }
rspec ./spec/amq/protocol/table_spec.rb:69 # AMQ::Protocol::Table.encode should return "\u0000\u0000\u0000\u000F\u0005floatd?\xFE\xB8Q\xEB\x85\u001E\xB8" for {"float"=>1.92}
rspec ./spec/amq/protocol/table_spec.rb:112 # AMQ::Protocol::Table.decode is capable of decoding string table values with UTF-8 characters
rspec ./spec/amq/protocol/table_spec.rb:203 # AMQ::Protocol::Table.decode is capable of decoding deeply nested tables
```

The failures in 2.2.1:
```
  1) AMQ::Protocol::Table.encode should serialize { :coordinates => { :latitude  => 59.35 } }
     Failure/Error: expect(Table.encode(:coordinates => { :latitude  => 59.35 })).to eql("\x00\x00\x00#\vcoordinatesF\x00\x00\x00\x12\blatituded@M\xAC\xCC\xCC\xCC\xCC\xCD")
       
       expected: "\u0000\u0000\u0000#\vcoordinatesF\u0000\u0000\u0000\u0012\blatituded@M\xAC\xCC\xCC\xCC\xCC\xCD"
            got: "\x00\x00\x00#\vcoordinatesF\x00\x00\x00\x12\blatituded@M\xAC\xCC\xCC\xCC\xCC\xCD"
       
       (compared using eql?)
     # ./spec/amq/protocol/table_spec.rb:61:in `block (3 levels) in <module:Protocol>'

  2) AMQ::Protocol::Table.encode should serialize { :coordinates => { :longitude => 18.066667 } }
     Failure/Error: expect(Table.encode(:coordinates => { :longitude => 18.066667 })).to eql("\x00\x00\x00$\vcoordinatesF\x00\x00\x00\x13\tlongituded@2\x11\x11\x16\xA8\xB8\xF1")
       
       expected: "\u0000\u0000\u0000$\vcoordinatesF\u0000\u0000\u0000\u0013\tlongituded@2\u0011\u0011\u0016\xA8\xB8\xF1"
            got: "\x00\x00\x00$\vcoordinatesF\x00\x00\x00\x13\tlongituded@2\x11\x11\x16\xA8\xB8\xF1"
       
       (compared using eql?)
     # ./spec/amq/protocol/table_spec.rb:65:in `block (3 levels) in <module:Protocol>'

  3) AMQ::Protocol::Table.encode should return "\u0000\u0000\u0000\u000F\u0005floatd?\xFE\xB8Q\xEB\x85\u001E\xB8" for {"float"=>1.92}
     Failure/Error: expect(Table.encode(data)).to eql(encoded)
       
       expected: "\u0000\u0000\u0000\u000F\u0005floatd?\xFE\xB8Q\xEB\x85\u001E\xB8"
            got: "\x00\x00\x00\x0F\x05floatd?\xFE\xB8Q\xEB\x85\x1E\xB8"
       
       (compared using eql?)
     # ./spec/amq/protocol/table_spec.rb:70:in `block (4 levels) in <module:Protocol>'

  4) AMQ::Protocol::Table.decode is capable of decoding string table values with UTF-8 characters
     Failure/Error: expect(Table.decode(Table.encode(input))).to eq(input)
     ArgumentError:
       Not a valid type: "н"
       Data: "\u0000\u0000\u0000\"\fстрокаS\u0000\u0000\u0000\u0010значение"
       Unprocessed data: "ачение"
       Offset: 18
       Total size: 34
       Processed data: {}
     # ./lib/amq/protocol/table.rb:105:in `decode'
     # ./spec/amq/protocol/table_spec.rb:114:in `block (3 levels) in <module:Protocol>'

  5) AMQ::Protocol::Table.decode is capable of decoding deeply nested tables
     Failure/Error: expect(Table.decode(Table.encode(input))).to eq(input)
     Encoding::CompatibilityError:
       incompatible character encodings: ASCII-8BIT and UTF-8
     # ./lib/amq/protocol/table.rb:42:in `block in encode'
     # ./lib/amq/protocol/table.rb:35:in `each'
     # ./lib/amq/protocol/table.rb:35:in `encode'
     # ./lib/amq/protocol/table.rb:42:in `block in encode'
     # ./lib/amq/protocol/table.rb:35:in `each'
     # ./lib/amq/protocol/table.rb:35:in `encode'
     # ./lib/amq/protocol/table.rb:42:in `block in encode'
     # ./lib/amq/protocol/table.rb:35:in `each'
     # ./lib/amq/protocol/table.rb:35:in `encode'
     # ./spec/amq/protocol/table_spec.rb:221:in `block (3 levels) in <module:Protocol>'

Finished in 0.11542 seconds (files took 0.20092 seconds to load)
412 examples, 5 failures

Failed examples:

rspec ./spec/amq/protocol/table_spec.rb:60 # AMQ::Protocol::Table.encode should serialize { :coordinates => { :latitude  => 59.35 } }
rspec ./spec/amq/protocol/table_spec.rb:64 # AMQ::Protocol::Table.encode should serialize { :coordinates => { :longitude => 18.066667 } }
rspec ./spec/amq/protocol/table_spec.rb:69 # AMQ::Protocol::Table.encode should return "\u0000\u0000\u0000\u000F\u0005floatd?\xFE\xB8Q\xEB\x85\u001E\xB8" for {"float"=>1.92}
rspec ./spec/amq/protocol/table_spec.rb:112 # AMQ::Protocol::Table.decode is capable of decoding string table values with UTF-8 characters
rspec ./spec/amq/protocol/table_spec.rb:203 # AMQ::Protocol::Table.decode is capable of decoding deeply nested tables
```

### CODE REVIEW

**Comment by dbyron0** [comment]
OK, I fixed the first failure as it was the only one for 1.8.7.

**Comment by michaelklishin** [comment]
Now tests fail on anything above 1.8.7 ;)

**Comment by michaelklishin** [comment]
I think it's fine to drop 1.8.7 support. It hasn't had any sort of update in well over a year. The users who need 1.8.7 can use Bunny 1.7 with amq-protocol 1.9.2. In the meantime, we can move on to 1.9.3+.

**Comment by dbyron0** [comment]
I don't think 1.8.7 support is going to be tough to keep, but if it needs to go, so be it I suppose.  I could use a hand with the encoding-related failures post 1.8.7 though.

**Comment by michaelklishin** [comment]
OK, I'm happy to take a look later this week (a RabbitMQ release is imminent ;)).

**Comment by dbyron0** [comment]
Hope this additional commit to enable warnings and remove them is OK.

**Comment by michaelklishin** [comment]
@dbyron0 thank you. Is this ready to be reviewed? N.B. that we can drop Ruby pre-2.0 support now that Bunny 2.0 drops it.

**Comment by dbyron0** [comment]
I'm pretty sure the post 1.8.7 encoding failures remain.  I've also moved on from the project where I was using this so my motivation and availability have plummeted :(  I would love a hand moving this forward.

**Comment by michaelklishin** [comment]
@dbyron0 no worries, I'll take over. Thank you for your help!

**Pull request merged**
